### PR TITLE
Snake case prb

### PR DESCRIPTION
**Pull request by ANaaim**
## SnakeCased all that seemed necessary.
Linked to the issue #15 

As I understood it, it was only necessary to do it for function not classes and I chose to do it also on function with Qdot : 
For example TestQdot would become test_qdot even if q tend to be in majuscule.

Hope it work.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ipuch/bionc/22)

### CODE REVIEW

**Comment by Ipuch** [comment]
> As I understood it, it was only necessary to do it for function not classes and I chose to do it also on function with Qdot : For example TestQdot would become test_qdot even if q tend to be in majuscule.
> 
> Hope it work.
> 

Yes, it was necessary for methods only :+1: 
I agree with this refactor.

**Review by Ipuch — CHANGES_REQUESTED** [review]
> Reviewed 16 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ipuch/bionc/22)* status: 16 of 19 files reviewed, 3 unresolved discussions (waiting on @ANaaim)

___
*[`bionc/model_creation/c3d_data.py` line 32 at r3](https://reviewable.io/reviews/ipuch/bionc/22#-NFGhzui4ALWXyCvdDIA:-NFGhzui4ALWXyCvdDIB:b-bbkby4) ([raw file](https://github.com/ipuch/bionc/blob/6d5c90ba235b7a7c8834421c20029f08e337b77e/bionc/model_creation/c3d_data.py#L32)):*
> ```Python
>                 self.first_frame : self.last_frame,
>             ]
>         )
> ```

Are you sure you blacked with `black . -l120` ?



_Code quote:_
```Python
        return self._to_meter(
            self.ezc3d_data["data"]["points"][
                :,
                self._indices_in_c3d(marker_names),
                self.first_frame : self.last_frame,
            ]
        )
```
___
*[`bionc/utils/natural_coordinates.py` line 149 at r3](https://reviewable.io/reviews/ipuch/bionc/22#-NFGiLSU418gn_uXE8e-:-NFGiLSU418gn_uXE8e0:b-81ah1b) ([raw file](https://github.com/ipuch/bionc/blob/6d5c90ba235b7a7c8834421c20029f08e337b77e/bionc/utils/natural_coordinates.py#L149)):*
> ```Python
> 
>     @classmethod
>     def from_qi(cls, tuple_of_Q: tuple):
> ```

What is your opinion on this, should we modify all the variables with an uppercase Q into a lowercase q too?



_Code quote:_
```Python
from_qi(cls, tuple_of_Q: tuple):
```
___
*[`tests/test_natural_velocities.py` line 117 at r3](https://reviewable.io/reviews/ipuch/bionc/22#-NFGioOF4H8c8_AgZuov:-NFGioOF4H8c8_AgZuow:b-u9vglx) ([raw file](https://github.com/ipuch/bionc/blob/6d5c90ba235b7a7c8834421c20029f08e337b77e/tests/test_natural_velocities.py#L117)):*
> ```Python
>     qdot = np.concatenate((qdot1, qdot2), axis=0)
>     with pytest.raises(AttributeError, match="'numpy.ndarray' object has no attribute 'udot'"):
>         qdot.udot
> ```

This has nothing to do here as I said before, no problem, we will handle this, this time ! *peace*

**Comment by Ipuch** [comment]
Looking closer, I'm pretty sure you didn't black with -l120. Could you revert, the check did not detect that every line is below 120-character length. But now, the code is smaller than a A4 page width. 
After that looks good to me ! :)

**Comment by ANaaim** [comment]
> > As I understood it, it was only necessary to do it for function not classes and I chose to do it also on function with Qdot : For example TestQdot would become test_qdot even if q tend to be in majuscule.
> > Hope it work.
> 
> Yes, it was necessary for methods only 👍 I agree with this refactor.
> 
> Here is a little comment on git best practice again:
> 
>     * When you start a new PR, it should be from the master/main branch of your target repository and not your previous PR. Try to remember: "A branch, A PR."
> 
> 
> As for the other one, as we are small now, it's okay, but if I had asked for changes on the other PR, it would have messed up with this one. But this PR could have been accepted before the other one if better done.

==> Strange.... I created a branch just for that and pull requested from this branch directly... But I might not have understand what you meant. Let's have a visio just to be sure...

**Comment by ANaaim** [comment]
I have re-run black with the option -l120 on all files but no modification was done on the code so I do not understand from what the problem is coming.

**Comment by ANaaim** [comment]
> > > As I understood it, it was only necessary to do it for function not classes and I chose to do it also on function with Qdot : For example TestQdot would become test_qdot even if q tend to be in majuscule.
> > > Hope it work.
> > 
> > 
> > Yes, it was necessary for methods only 👍 I agree with this refactor.
> > Here is a little comment on git best practice again:
> > ```
> > * When you start a new PR, it should be from the master/main branch of your target repository and not your previous PR. Try to remember: "A branch, A PR."
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As for the other one, as we are small now, it's okay, but if I had asked for changes on the other PR, it would have messed up with this one. But this PR could have been accepted before the other one if better done.
> 
> ==> Strange.... I created a branch just for that and pull requested from this branch directly... But I might not have understand what you meant. Let's have a visio just to be sure...

I think, I understood what you mean... I have put the pull request on the wrong repertory ?

**Comment by ANaaim** [comment]
*[`bionc/model_creation/c3d_data.py` line 32 at r3](https://reviewable.io/reviews/ipuch/bionc/22#-NFGhzui4ALWXyCvdDIA:-NFJQhf9-iic2KlmF7Av:bnnefe5) ([raw file](https://github.com/ipuch/bionc/blob/6d5c90ba235b7a7c8834421c20029f08e337b77e/bionc/model_creation/c3d_data.py#L32)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Are you sure you blacked with `black . -l120` ?
</blockquote></details>

Yes i revalidated on the code it was blacked with the option -l120

**Comment by ANaaim** [comment]
*[`bionc/utils/natural_coordinates.py` line 149 at r3](https://reviewable.io/reviews/ipuch/bionc/22#-NFGiLSU418gn_uXE8e-:-NFJR5RV5QPcO5gbmh4j:b-y873jv) ([raw file](https://github.com/ipuch/bionc/blob/6d5c90ba235b7a7c8834421c20029f08e337b77e/bionc/utils/natural_coordinates.py#L149)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

What is your opinion on this, should we modify all the variables with an uppercase Q into a lowercase q too?
</blockquote></details>

I am not sure... The question should be is there any other element where we would need to have Q and q which would be different... I have to think about it ...

**Comment by ANaaim** [comment]
*[`tests/test_natural_velocities.py` line 117 at r3](https://reviewable.io/reviews/ipuch/bionc/22#-NFGioOF4H8c8_AgZuov:-NFJRQoj0pOELd2xCSY7:b-u1rf50) ([raw file](https://github.com/ipuch/bionc/blob/6d5c90ba235b7a7c8834421c20029f08e337b77e/tests/test_natural_velocities.py#L117)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

This has nothing to do here as I said before, no problem, we will handle this, this time ! *peace*
</blockquote></details>

I might have not understand a former demand....I will change its place ^^' Communication though text message might be difficult sometime ;)

**Comment by ANaaim** [comment]
@Ipuch : I think that the code is valid in its current state but i might be wrong.

**Review by Ipuch — CHANGES_REQUESTED** [review]
> Reviewed 11 of 14 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ipuch/bionc/22)* status: 17 of 19 files reviewed, 1 unresolved discussion (waiting on @ANaaim)

___
*[`bionc/model_creation/c3d_data.py` line 32 at r3](https://reviewable.io/reviews/ipuch/bionc/22#-NFGhzui4ALWXyCvdDIA:-NFUsNK-BmRkeWBZqlNC:b-v2swsh) ([raw file](https://github.com/ipuch/bionc/blob/6d5c90ba235b7a7c8834421c20029f08e337b77e/bionc/model_creation/c3d_data.py#L32)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

Yes i revalidated on the code it was blacked with the option -l120
</blockquote></details>

It wasn't, I forced pushed and black with -l120.

**Review by Ipuch — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ipuch/bionc/22#-:-NFUtVsz9irJ0_XQgNnH:bnfp4nl)* status: 17 of 19 files reviewed, all discussions resolved

**Pull request merged**
