### PR TITLE
Creation of full coverage of natural_velocities

### PR DESCRIPTION
**Pull request by ANaaim**
This change is [Reviewable](https://reviewable.io/reviews/ipuch/bionc/13)

### CODE REVIEW

**Comment by ANaaim** [comment]
Strange I used the command black test_natural_velocities.py and it returned that the file was left unchanged ....

**Comment by Ipuch** [comment]
For the next time, a PR doesn't need to be closed if the tests are not working yet. Keep it open until it pass 😉

It helps to track the changes.

**Review by ANaaim — COMMENTED** [review]
Noted for later :) 

> *[Reviewable](https://reviewable.io/reviews/ipuch/bionc/13#-:-NEuRJGp8XkNXt5CsHO0:bcqfj07)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by Ipuch** [comment]
@ANaaim also, you can mention the issue like this to link it to issue #11 . This pull request will appear in the issue :+1:

**Review by Ipuch — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ipuch/bionc/13)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ANaaim)

*[a discussion](https://reviewable.io/reviews/ipuch/bionc/13#-NEuuEXX9jM5EzkK8UoK:-NEuuEXY8Vwo4pwqNmD_:bph6fwp) (no related file):*
Nicely done, would be able to remove the unnecessary tests in test: test_natural_coordinates.py ?

I tested natural velocities in it in may be redundant

___

**Comment by ANaaim** [comment]
Test mention to an issue : #11

**Review by ANaaim — COMMENTED** [review]
Where can we see the changes request ? 

> *[Reviewable](https://reviewable.io/reviews/ipuch/bionc/13#-:-NEv0Z5B6dTtKhxYSjon:bg3jx4f)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Ipuch)

**Comment by ANaaim** [comment]
> > _[Reviewable](https://reviewable.io/reviews/ipuch/bionc/13)_ status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ANaaim)
> 
> _[a discussion](https://reviewable.io/reviews/ipuch/bionc/13#-NEuuEXX9jM5EzkK8UoK:-NEuuEXY8Vwo4pwqNmD_:bph6fwp) (no related file):_ Nicely done, would be able to remove the unnecessary tests in test: test_natural_coordinates.py ?
> 
> I tested natural velocities in it in may be redundant

This has been taken into account in the third commit

**Review by Ipuch — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ipuch/bionc/13)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ANaaim)

___
*[`tests/test_natural_coordinates.py` line 42 at r4](https://reviewable.io/reviews/ipuch/bionc/13#-NEvpVVM0WvvdwXpq94m:-NEvpVVM0WvvdwXpq94n:b-25h5a5) ([raw file](https://github.com/ipuch/bionc/blob/16cd330b021b41c706b3ea03ddc3014de52ddd00/tests/test_natural_coordinates.py#L42)):*
> ```Python
>     np.testing.assert_equal(Qdoti.rpdot, np.array([10, 11, 12]))
>     np.testing.assert_equal(Qdoti.vector, Qdoti)
> ```

This should be in test_natural_velocity.py too 



_Code quote:_
```Python
def test_SegmentNaturalVelocitiesCreator():
    Qdoti = SegmentNaturalVelocities.from_components(
        udot=np.array([1, 2, 3]),
        wdot=np.array([4, 5, 6]),
        rddot=np.array([7, 8, 9]),
        rpdot=np.array([10, 11, 12]),
    )
    np.testing.assert_equal(Qdoti.udot, np.array([1, 2, 3]))
    np.testing.assert_equal(Qdoti.wdot, np.array([4, 5, 6]))
    np.testing.assert_equal(Qdoti.rddot, np.array([7, 8, 9]))
    np.testing.assert_equal(Qdoti.rpdot, np.array([10, 11, 12]))
    np.testing.assert_equal(Qdoti.vector, Qdoti)
```
___
*[`tests/test_natural_coordinates.py` line 96 at r4](https://reviewable.io/reviews/ipuch/bionc/13#-NEvphOKCJPBMFqbxUqQ:-NEvphOKCJPBMFqbxUqR:b-o4eash) ([raw file](https://github.com/ipuch/bionc/blob/16cd330b021b41c706b3ea03ddc3014de52ddd00/tests/test_natural_coordinates.py#L96)):*
> ```Python
>     Qdot = np.concatenate((Qdot1, Qdot2), axis=0)
>     with pytest.raises(AttributeError, match="'numpy.ndarray' object has no attribute 'udot'"):
>         Qdot.udot
> ```

Also this one  and we are good to merge :+1: 



_Code quote:_
```Python
def test_concatenate_velocities():
    Qdot1 = SegmentNaturalVelocities.from_components(
        udot=np.array([1, 2, 3]),
        wdot=np.array([4, 5, 6]),
        rddot=np.array([7, 8, 9]),
        rpdot=np.array([10, 11, 12]),
    )
    Qdot2 = SegmentNaturalVelocities.from_components(
        udot=np.array([11, 22, 33]),
        wdot=np.array([4, 5, 6]),
        rddot=np.array([7, 82, 9]),
        rpdot=np.array([110, 11, 12]),
    )
    Qdot = np.concatenate((Qdot1, Qdot2), axis=0)
    with pytest.raises(AttributeError, match="'numpy.ndarray' object has no attribute 'udot'"):
        Qdot.udot
```

**Comment by Ipuch** [comment]
Related to #5 also

**Review by ANaaim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ipuch/bionc/13)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Ipuch)

___
*[`tests/test_natural_coordinates.py` line 42 at r4](https://reviewable.io/reviews/ipuch/bionc/13#-NEvpVVM0WvvdwXpq94m:-NFD1RWu1cpLz2-xq11x:bs7wua9) ([raw file](https://github.com/ipuch/bionc/blob/16cd330b021b41c706b3ea03ddc3014de52ddd00/tests/test_natural_coordinates.py#L42)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

This should be in test_natural_velocity.py too 
</blockquote></details>

Done 
___
*[`tests/test_natural_coordinates.py` line 96 at r4](https://reviewable.io/reviews/ipuch/bionc/13#-NEvphOKCJPBMFqbxUqQ:-NFD1Tnw1Gai77i_1ycZ:b-896fjx) ([raw file](https://github.com/ipuch/bionc/blob/16cd330b021b41c706b3ea03ddc3014de52ddd00/tests/test_natural_coordinates.py#L96)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Also this one  and we are good to merge :+1: 
</blockquote></details>

Done

**Comment by Ipuch** [comment]
Small issues with this PR, here are some good practices for the next PR:

-  Avoid doing a PR from your main branch, as it sometimes requires me to commit to your PR, I can commit on your other branch with which you opened a PR, except with your main branch
- Don't merge with the master yourself in the PR because I will need to review the modification related to the merge, best practice is to merge once we finish the PR. Exceptions can arise if the current PR is deeply related to previous PRs.

Since I cannot commit, I'll need to open a new pull request based on your branch. This is fine anyway, I can back on my feet!

**Review by Ipuch — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ipuch/bionc/13)* status: all files reviewed, 2 unresolved discussions (waiting on @ANaaim)

**Review by Ipuch — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ipuch/bionc/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ANaaim)

**Review by Ipuch — APPROVED** [review]
Almost LTGM

> *[Reviewable](https://reviewable.io/reviews/ipuch/bionc/13#-:-NFGdkNDAglKPZNApZGA:bo5fqtr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ANaaim)

**Review by Ipuch — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ipuch/bionc/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ANaaim)

**Pull request merged**
