### PR TITLE
[WIP] #76 Add General Spherical joint 

### PR DESCRIPTION
**Pull request by ANaaim**
* [X] Linked issue related to your pull request using #76
* [X] Used the tag [WIP] or [RTR] for on-going changes, or for ready to review
* [In progress ] Did you write new tests to cover your changes?
* [In progress ] Did you write a proper documentation (docstrings and ReadMe)
* [X ] Please black your code `black . -l120`
* [x] make sure the test still pass after solving comments.
* [ ] build new test to cover the changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/85)

### CODE REVIEW

**Review by Ipuch — CHANGES_REQUESTED** [review]
Here is my little comments.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/85#-:-NdpBBhj6y2haBa1msao:bgait4p)* status: all files reviewed, 11 unresolved discussions (waiting on @ANaaim)

___
*[`bionc/bionc_casadi/enums.py` line 21 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpB3G0EVHIYtugeuF-:-NdpB3G0EVHIYtugeuF0:b-8jphnh) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_casadi/enums.py#L21)):*
> ```Python
>     UNIVERSAL = Joint.Universal
>     SPHERICAL = Joint.Spherical
>     GENERAL_SPHERICAL = Joint.GeneralSpherical
> ```

to be removed
___
*[`bionc/bionc_casadi/joint.py` line 415 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-Ndp3oStBuqbNF3pAzxM:-Ndp3oStBuqbNF3pAzxN:bsihfgi) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_casadi/joint.py#L415)):*
> ```Python
>             ), self.child_constraint_jacobian_derivative(Qdot_parent, Qdot_child)
> 
>     class GeneralSpherical(JointBase):
> ```

Like said in the issue #76 , we should merge the feature of the existing class Spherical. 
The default behavior should take parent and child as default points, or it should use the specified points, if any.
___
*[`bionc/bionc_casadi/joint.py` line 438 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-Ndp4bx51Ks_K_gHv8_j:-Ndp4bx6-sz4R4dUFK4s:b-6gxmzk) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_casadi/joint.py#L438)):*
> ```Python
> 
>             self.nb_constraints = 3
>             self.parent_point = parent.marker_from_name(parent_point)
> ```

In the future class
```python3
self.parent_point = (
    NaturalMarker(  
        name=f"{self.name}_parent_point",  
        position=NaturalVector.distal(),  
        is_technical=False,  
        is_anatomical=True,  
    )  
 if parent_point is None else parent.marker_from_name(parent_point)
)

self.parent_point = (
    NaturalMarker(  
        name=f"{self.name}_child_point",  
        position=NaturalVector.proximal(),  
        is_technical=False,  
        is_anatomical=True,  
    )  
 if parent_point is None else parent.marker_from_name(parent_point)
)

```
___
*[`bionc/bionc_casadi/joint.py` line 439 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpA2p-4HGfHHmWp4_N:-NdpA2p-4HGfHHmWp4_O:b-ecpln1) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_casadi/joint.py#L439)):*
> ```Python
>             self.nb_constraints = 3
>             self.parent_point = parent.marker_from_name(parent_point)
>             self.child_point = child.marker_from_name(child_point)
> ```

Explained over this.
___
*[`bionc/bionc_casadi/joint.py` line 470 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpAQxhBqm0l-mC4ahN:-NdpAQxhBqm0l-mC4ahO:b-imhefp) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_casadi/joint.py#L470)):*
> ```Python
>         ) -> MX:
>             K_k_parent = MX.zeros((self.nb_constraints, 12))
>             K_k_parent[:3, 6:9] = self.parent_point.interpolation_matrix
> ```

I think the slicing should be `[:3, : ]`
___
*[`bionc/bionc_casadi/joint.py` line 478 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpAa_QBI-ml-OM1zk1:-NdpAa_QBI-ml-OM1zk2:bb7i16w) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_casadi/joint.py#L478)):*
> ```Python
>         ) -> MX:
>             K_k_child = MX.zeros((self.nb_constraints, 12))
>             K_k_child[:3, 3:6] = -self.child_point.interpolation_matrix
> ```

idem
___
*[`bionc/bionc_numpy/enums.py` line 21 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpAhNgEjWENG2SQfrx:-NdpAhNgEjWENG2SQfry:b-8jphnh) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_numpy/enums.py#L21)):*
> ```Python
>     UNIVERSAL = Joint.Universal
>     SPHERICAL = Joint.Spherical
>     GENERAL_SPHERICAL = Joint.GeneralSpherical
> ```

to be removed
___
*[`bionc/bionc_numpy/joint.py` line 513 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpAm9Q9g5hhrFEAIAF:-NdpAm9Q9g5hhrFEAIAG:b-307vfk) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_numpy/joint.py#L513)):*
> ```Python
>             self.nb_constraints = 3
>             self.parent_point = parent.marker_from_name(parent_point)
>             self.child_point = child.marker_from_name(child_point)
> ```

same comment as for casadi
___
*[`bionc/bionc_numpy/joint.py` line 544 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpAr3Q4TNq05RwAlsJ:-NdpAr3Q4TNq05RwAlsK:byjdhc2) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_numpy/joint.py#L544)):*
> ```Python
>         ) -> np.ndarray:
>             K_k_parent = np.zeros((self.nb_constraints, 12))
>             K_k_parent[:3, 6:9] = self.parent_point.interpolation_matrix
> ```

same slicing error
___
*[`bionc/bionc_numpy/joint.py` line 552 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpAtxI9pKkbZ4v0hDI:-NdpAtxI9pKkbZ4v0hDJ:byjdhc2) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_numpy/joint.py#L552)):*
> ```Python
>         ) -> np.ndarray:
>             K_k_child = np.zeros((self.nb_constraints, 12))
>             K_k_child[:3, 3:6] = -self.child_point.interpolation_matrix
> ```

same slicing error
___
*[`bionc/bionc_numpy/joint.py` line 611 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpAyAU7N7G6E8t5eon:-NdpAyAU7N7G6E8t5eoo:b-t3pm57) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_numpy/joint.py#L611)):*
> ```Python
>                 The joint as a mx joint
>             """
>             # TODO: implement this in joint casadi
> ```

should be fined to remove if Done, I guess.

**Review by Ipuch — CHANGES_REQUESTED** [review]
Almost done ! I like the fact you spotted some errors in my docstrings 🙈
Please clic on the violet button "Reviewable", to write "Done" under each comment that has been treated.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/85#-:-Ne4WqPF2mlqHy6U7dTu:bk47cq4)* status: all files reviewed, 12 unresolved discussions (waiting on @ANaaim)

___
*[`bionc/bionc_casadi/joint.py` line 415 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-Ndp3oStBuqbNF3pAzxM:-Ne4W6-z21ZIvYEDD6Vf:bjphkp6) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_casadi/joint.py#L415)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Like said in the issue #76 , we should merge the feature of the existing class Spherical. 
The default behavior should take parent and child as default points, or it should use the specified points, if any.
</blockquote></details>

Please write "Done" under each comment is treated, so I can remove the comments when the action has been done.
___
*[`bionc/bionc_casadi/joint.py` line 342 at r2](https://reviewable.io/reviews/Ipuch/bioNC/85#-Ne4T8uI0_PbaQNPeXbm:-Ne4T8uJ77TOPPBg0X-k:b-duzv86) ([raw file](https://github.com/Ipuch/bioNC/blob/632e16bf583527aed0bb2cda349885534545154e/bionc/bionc_casadi/joint.py#L342)):*
> ```Python
>         ):
>             super(Joint.Spherical, self).__init__(
>                 name, parent, child, index, parent_point, child_point, projection_basis, parent_basis, child_basis
> ```

"parent_point", "child_point" have to be removed, that's why the tests are not passing.
"Super" calls the parent class  `JointBase` that has common entries for every joint. As all joints doesn't have a parent and child point yet. 

It's not relevant to initialize them now. But this would be a great idea in the future ! 
Then, to initialize parent and child point with proximal and distal point would be automated for every joint, in the parent class `JointBase`  to avoid redundancy.

1) So, can you remove it for now? And make your PR pass.
2) Can you open an issue about it ? :)

**Comment by ANaaim** [comment]
*[`bionc/bionc_casadi/joint.py` line 415 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-Ndp3oStBuqbNF3pAzxM:-Ne74PbS4L-oNVFCXvqI:b-896fjx) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_casadi/joint.py#L415)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Please write "Done" under each comment is treated, so I can remove the comments when the action has been done.
</blockquote></details>

Done

**Review by Ipuch — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/85)* status: all files reviewed, 11 unresolved discussions (waiting on @ANaaim)

**Review by Ipuch — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/85)* status: all files reviewed, 11 unresolved discussions (waiting on @ANaaim)

**Comment by ANaaim** [comment]
*[`bionc/bionc_numpy/joint.py` line 513 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpAm9Q9g5hhrFEAIAF:-NeCpmCB86S0eduVnEi5:b-896fjx) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_numpy/joint.py#L513)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

same comment as for casadi
</blockquote></details>

Done

**Comment by ANaaim** [comment]
*[`bionc/bionc_numpy/joint.py` line 544 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpAr3Q4TNq05RwAlsJ:-Ne73a1z7AobX8-yZozb:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_numpy/joint.py#L544)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

same slicing error
</blockquote></details>

Done.

**Comment by ANaaim** [comment]
*[`bionc/bionc_numpy/joint.py` line 611 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpAyAU7N7G6E8t5eon:-NeCprXs1M27_11YWiK0:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_numpy/joint.py#L611)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

should be fined to remove if Done, I guess.
</blockquote></details>

Done

**Comment by ANaaim** [comment]
*[`bionc/bionc_casadi/joint.py` line 342 at r2](https://reviewable.io/reviews/Ipuch/bioNC/85#-Ne4T8uI0_PbaQNPeXbm:-NeCqalo0PiVKRRmLq3c:b-flxaw7) ([raw file](https://github.com/Ipuch/bioNC/blob/632e16bf583527aed0bb2cda349885534545154e/bionc/bionc_casadi/joint.py#L342)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

"parent_point", "child_point" have to be removed, that's why the tests are not passing.
"Super" calls the parent class  `JointBase` that has common entries for every joint. As all joints doesn't have a parent and child point yet. 

It's not relevant to initialize them now. But this would be a great idea in the future ! 
Then, to initialize parent and child point with proximal and distal point would be automated for every joint, in the parent class `JointBase`  to avoid redundancy.

1) So, can you remove it for now? And make your PR pass.
2) Can you open an issue about it ? :)
</blockquote></details>

Done (Both)

**Review by ANaaim — COMMENTED** [review]
Done 

> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/85#-:-NeCpvXQ0tdPooxvF3yj:b-896fjb)* status: all files reviewed, 11 unresolved discussions (waiting on @Ipuch)

___
*[`bionc/bionc_casadi/joint.py` line 438 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-Ndp4bx51Ks_K_gHv8_j:-Ne73ScqCmcE0i2uxBZ1:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_casadi/joint.py#L438)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

In the future class
```python3
self.parent_point = (
    NaturalMarker(  
        name=f"{self.name}_parent_point",  
        position=NaturalVector.distal(),  
        is_technical=False,  
        is_anatomical=True,  
    )  
 if parent_point is None else parent.marker_from_name(parent_point)
)

self.parent_point = (
    NaturalMarker(  
        name=f"{self.name}_child_point",  
        position=NaturalVector.proximal(),  
        is_technical=False,  
        is_anatomical=True,  
    )  
 if parent_point is None else parent.marker_from_name(parent_point)
)

```
</blockquote></details>

Done.
___
*[`bionc/bionc_casadi/joint.py` line 439 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpA2p-4HGfHHmWp4_N:-Ne73UfsBa3Wd6mvt3CS:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_casadi/joint.py#L439)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Explained over this.
</blockquote></details>

Done.
___
*[`bionc/bionc_casadi/joint.py` line 470 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpAQxhBqm0l-mC4ahN:-Ne73VYb1ib8JKUiku9I:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_casadi/joint.py#L470)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

I think the slicing should be `[:3, : ]`
</blockquote></details>

Done.
___
*[`bionc/bionc_casadi/joint.py` line 478 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpAa_QBI-ml-OM1zk1:-Ne73WIz-CSSVyqc2oTs:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_casadi/joint.py#L478)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

idem
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/joint.py` line 552 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpAtxI9pKkbZ4v0hDI:-Ne73_j74mQQHAGR4IQV:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_numpy/joint.py#L552)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

same slicing error
</blockquote></details>

Done.
___
*[`bionc/bionc_casadi/enums.py` line 21 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpB3G0EVHIYtugeuF-:-Ne73e1X9YK5HyzMe59Q:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_casadi/enums.py#L21)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

to be removed
</blockquote></details>

Done.
___
*[`bionc/bionc_numpy/enums.py` line 21 at r1](https://reviewable.io/reviews/Ipuch/bioNC/85#-NdpAhNgEjWENG2SQfrx:-Ne73f46EMXc69qjmh8n:b-896fix) ([raw file](https://github.com/Ipuch/bioNC/blob/a29554fb4fcaae70f68f460cf8fecbd79f78ba1b/bionc/bionc_numpy/enums.py#L21)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

to be removed
</blockquote></details>

Done.

**Review by Ipuch — CHANGES_REQUESTED** [review]
black, and ready to merge I think !!

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/85#-:-NeDZcRW-pk7UxQbzepe:b-i093du)* status: all files reviewed, 2 unresolved discussions (waiting on @ANaaim)

___
*[`tests/test_joints.py` line 100 at r5](https://reviewable.io/reviews/Ipuch/bioNC/85#-NeDYg1J3KCkvOQmcCrR:-NeDYg1J3KCkvOQmcCrS:b7ol6t9) ([raw file](https://github.com/Ipuch/bioNC/blob/6aac3074261cd25be401ae71bcb755c716240f5e/tests/test_joints.py#L100)):*
> ```Python
>         assert joint.nb_joint_dof == 3
>         assert joint.nb_constraints == 3
> ```

Just put a comment to explain why we need two joints, or name them better:
"joint_distal_proximal" and "joint_custom_location".
___
*[`tests/test_joints.py` line 706 at r5](https://reviewable.io/reviews/Ipuch/bioNC/85#-NeDZOJV5ldx0ii_wfMq:-NeDZOJV5ldx0ii_wfMr:b-d5kjr9) ([raw file](https://github.com/Ipuch/bioNC/blob/6aac3074261cd25be401ae71bcb755c716240f5e/tests/test_joints.py#L706)):*
> ```Python
> #
> # jacobian_mx = j_jacobian_func(np.arange(24)).toarray()
> # def joint_spherical_not_distal_proximal():
> ```

plz remove the last line. :)

**Comment by ANaaim** [comment]
*[`tests/test_joints.py` line 706 at r5](https://reviewable.io/reviews/Ipuch/bioNC/85#-NeDZOJV5ldx0ii_wfMq:-NeE18J6-aBLK0huIyQx:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/6aac3074261cd25be401ae71bcb755c716240f5e/tests/test_joints.py#L706)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

plz remove the last line. :)
</blockquote></details>

Done

**Comment by ANaaim** [comment]
*[`tests/test_joints.py` line 100 at r5](https://reviewable.io/reviews/Ipuch/bioNC/85#-NeDYg1J3KCkvOQmcCrR:-NeE14wwDK6nB4SFxG3T:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/6aac3074261cd25be401ae71bcb755c716240f5e/tests/test_joints.py#L100)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Just put a comment to explain why we need two joints, or name them better:
"joint_distal_proximal" and "joint_custom_location".
</blockquote></details>

Done

**Comment by ANaaim** [comment]
Done

**Review by Ipuch — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/85#-:-NeE3NPm4qu0Gw1uu4oa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ANaaim)

**Pull request merged**
