### PR TITLE
Add some static function to construct some model with cross product of axis

### PR DESCRIPTION
**Pull request by ANaaim**
Some function have been added to be able to construct model using vector instead of point. Not sure if they were positionned in the correct function and if these function might have alredy existed in the code but I did not find them. 

The inspiration is from the static function in marker_template. If the function are ok. I can eventually add some testing in from it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/89)

### CODE REVIEW

**Review by Ipuch — CHANGES_REQUESTED** [review]
One small review + It would require a simple unit test to test these new function :)

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/89#-:-NfL_v8DEKhukkEXDv-r:bymiyqu)* status: all files reviewed, 5 unresolved discussions (waiting on @ANaaim)

___
*[`bionc/model_creation/natural_axis_template.py` line 46 at r1](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfLZ9111S7jhc-WpwCZ:-NfLZ9111S7jhc-WpwC_:b-9t23cp) ([raw file](https://github.com/Ipuch/bioNC/blob/6224566e7e2a381c0dfba2856e8c5b1173ae62b9/bionc/model_creation/natural_axis_template.py#L46)):*
> ```Python
> 
>     @staticmethod
>     def normal_to_vectors(m, bio, v1: np.ndarray, v2: np.ndarray) -> np.ndarray:
> ```

what to think to call the function normalized_cross_product ?
___
*[`bionc/model_creation/natural_axis_template.py` line 46 at r1](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfL_g2q6aumcmx-sbBt:-NfL_g2q6aumcmx-sbBu:b6l1jsq) ([raw file](https://github.com/Ipuch/bioNC/blob/6224566e7e2a381c0dfba2856e8c5b1173ae62b9/bionc/model_creation/natural_axis_template.py#L46)):*
> ```Python
> 
>     @staticmethod
>     def normal_to_vectors(m, bio, v1: np.ndarray, v2: np.ndarray) -> np.ndarray:
> ```

Add a numpy docstring like the previous function.
___
*[`bionc/model_creation/natural_axis_template.py` line 47 at r1](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfLZZ0D4qCD6MLdzc8I:-NfLZZ0D4qCD6MLdzc8J:b87zufe) ([raw file](https://github.com/Ipuch/bioNC/blob/6224566e7e2a381c0dfba2856e8c5b1173ae62b9/bionc/model_creation/natural_axis_template.py#L47)):*
> ```Python
>     @staticmethod
>     def normal_to_vectors(m, bio, v1: np.ndarray, v2: np.ndarray) -> np.ndarray:
>         v = np.ones((4, v1.shape[1]))
> ```

variable v renamed to 'normalized_vector' ?
___
*[`bionc/model_creation/natural_axis_template.py` line 47 at r1](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfLZiNt3K5B6MNf_RbP:-NfLZiNt3K5B6MNf_RbQ:bii326n) ([raw file](https://github.com/Ipuch/bioNC/blob/6224566e7e2a381c0dfba2856e8c5b1173ae62b9/bionc/model_creation/natural_axis_template.py#L47)):*
> ```Python
>     @staticmethod
>     def normal_to_vectors(m, bio, v1: np.ndarray, v2: np.ndarray) -> np.ndarray:
>         v = np.ones((4, v1.shape[1]))
> ```

I believe you would like to have np.zeros()

because when use homogenous transform, you don't mind about the point of application of a pure vector ?
___
*[`bionc/model_creation/natural_axis_template.py` line 56 at r1](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfL_6tBASdqX2ciNl_C:-NfL_6tC0xh28E3nFHWA:bqoxm6u) ([raw file](https://github.com/Ipuch/bioNC/blob/6224566e7e2a381c0dfba2856e8c5b1173ae62b9/bionc/model_creation/natural_axis_template.py#L56)):*
> ```Python
> 
>     @staticmethod
>     def from_start_to_end(m, bio, start: np.ndarray | str, end: np.ndarray) -> np.ndarray:
> ```

What is the purpose here? I find it very misleading because the class is supposed to be built to do this. Get a look at the init.
If you cannot convince me it's absolutely needed, I would remove it.

Plus, I don't understand why it could take an entry for start as a np.ndarray or str and not for end.

**Comment by ANaaim** [comment]
*[`bionc/model_creation/natural_axis_template.py` line 46 at r1](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfLZ9111S7jhc-WpwCZ:-NfPQi7VDqPnd1ADZzZ9:bbxm9v8) ([raw file](https://github.com/Ipuch/bioNC/blob/6224566e7e2a381c0dfba2856e8c5b1173ae62b9/bionc/model_creation/natural_axis_template.py#L46)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

what to think to call the function normalized_cross_product ?
</blockquote></details>

I am not great with naming function, so for me it is ok

**Comment by ANaaim** [comment]
*[`bionc/model_creation/natural_axis_template.py` line 46 at r1](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfLZ9111S7jhc-WpwCZ:-NfPRWNkDXpcnwejYdhm:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/6224566e7e2a381c0dfba2856e8c5b1173ae62b9/bionc/model_creation/natural_axis_template.py#L46)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

I am not great with naming function, so for me it is ok
</blockquote></details>

Done

**Comment by ANaaim** [comment]
*[`bionc/model_creation/natural_axis_template.py` line 46 at r1](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfL_g2q6aumcmx-sbBt:-NfPRgy5BPc3lXhJrC2S:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/6224566e7e2a381c0dfba2856e8c5b1173ae62b9/bionc/model_creation/natural_axis_template.py#L46)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Add a numpy docstring like the previous function.
</blockquote></details>

Done

**Comment by ANaaim** [comment]
*[`bionc/model_creation/natural_axis_template.py` line 47 at r1](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfLZZ0D4qCD6MLdzc8I:-NfPRigi9XMlu2MEtMQr:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/6224566e7e2a381c0dfba2856e8c5b1173ae62b9/bionc/model_creation/natural_axis_template.py#L47)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

variable v renamed to 'normalized_vector' ?
</blockquote></details>

Done

**Comment by ANaaim** [comment]
*[`bionc/model_creation/natural_axis_template.py` line 47 at r1](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfLZiNt3K5B6MNf_RbP:-NfPRmGm-n_fRvwLXRCw:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/6224566e7e2a381c0dfba2856e8c5b1173ae62b9/bionc/model_creation/natural_axis_template.py#L47)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

I believe you would like to have np.zeros()

because when use homogenous transform, you don't mind about the point of application of a pure vector ?
</blockquote></details>

Done

**Comment by ANaaim** [comment]
*[`bionc/model_creation/natural_axis_template.py` line 56 at r1](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfL_6tBASdqX2ciNl_C:-NfPRqU-2_Yn0h2o-8v_:bgfywt2) ([raw file](https://github.com/Ipuch/bioNC/blob/6224566e7e2a381c0dfba2856e8c5b1173ae62b9/bionc/model_creation/natural_axis_template.py#L56)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

What is the purpose here? I find it very misleading because the class is supposed to be built to do this. Get a look at the init.
If you cannot convince me it's absolutely needed, I would remove it.

Plus, I don't understand why it could take an entry for start as a np.ndarray or str and not for end.
</blockquote></details>

I did not find any way to generate a numpy array from the axis/axistemplate object to be processed for creating the model ==> so I added this function. Might not be necessary, but i need to know how to generate the vector from the axis object.

**Comment by Ipuch** [comment]
Can you show me a minimal example of the use of your second function. So that I can evaluate the relevance ?

**Review by Ipuch — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/89)* status: all files reviewed, 1 unresolved discussion (waiting on @ANaaim)

**Comment by ANaaim** [comment]
Thats the former name of the function :
```python
vrshank = lambda m, bio: AxisTemplate.from_start_to_end(
        m, bio, start="right_ankle", end="right_knee"
    )  # vérifier que v va bien du distal au proximal
    wrshank = lambda m, bio: MarkerTemplate.normal_to(m, bio, "right_ankle", midRToes(m, bio), "right_knee")

    model["RSHANK"] = SegmentTemplate(
        natural_segment=NaturalSegmentTemplate(
            u_axis=AxisFunctionTemplate(
                function=lambda m, bio: AxisTemplate.normal_to_vectors(m, bio, vrshank(m, bio), wrshank(m, bio))
            ),
            proximal_point=lambda m, bio: m["right_knee"],
            distal_point=lambda m, bio: m["right_ankle"],
            w_axis=AxisFunctionTemplate(
                function=lambda m, bio: MarkerTemplate.normal_to(m, bio, "right_ankle", midRToes(m, bio), "right_knee")
            ),
        )
    )
```

**Comment by Ipuch** [comment]
Here is the devil :smiling_imp: :
> ```python
> vrshank = lambda m, bio: AxisTemplate.from_start_to_end(
>         m, bio, start="right_ankle", end="right_knee"
>     )  # vérifier que v va bien du distal au proximal
> ```
Revised:
> ```python
> vrshank = lambda m, bio: Axis(start=Marker(position=m["right_ankle"]), end=Marker(position=m["right_knee"])).to_axis()
> ```
We could modify the class to authorize np.ndarray as entries:
https://github.com/Ipuch/bioNC/blob/d7a9a92bd49643bc3224885f7791131678bcfb48/bionc/bionc_numpy/natural_axis.py#L10-L20

Now I am convinced the function you coded as not is placed here ` AxisTemplate  ` :)


These two lines should not need to be a lambda function if it's stored in the c3d
> ```python
>             proximal_point=lambda m, bio: m["right_knee"],
>             distal_point=lambda m, bio: m["right_ankle"],
> ```
Revised:
> ```python
>             proximal_point="right_knee",
>             distal_point="right_ankle",
> ```

**Review by Ipuch — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/89)* status: all files reviewed, 2 unresolved discussions (waiting on @ANaaim)

___
*[`bionc/model_creation/natural_axis_template.py` line 56 at r1](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfL_6tBASdqX2ciNl_C:-NfRTQsV0dfuZletGzN6:b-n6d6dn) ([raw file](https://github.com/Ipuch/bioNC/blob/6224566e7e2a381c0dfba2856e8c5b1173ae62b9/bionc/model_creation/natural_axis_template.py#L56)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

I did not find any way to generate a numpy array from the axis/axistemplate object to be processed for creating the model ==> so I added this function. Might not be necessary, but i need to know how to generate the vector from the axis object.
</blockquote></details>

Please remove
___
*[`bionc/model_creation/natural_axis_template.py` line 51 at r2](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfRTUlUDfDHJMYzksrM:-NfRTUlUDfDHJMYzksrN:b-rgx397) ([raw file](https://github.com/Ipuch/bioNC/blob/ebdd5120ec7b3ca5a91eb855d4c2ca5978dc05ee/bionc/model_creation/natural_axis_template.py#L51)):*
> ```Python
>         Parameters
>         ----------
>         m : dict of markers
> ```

it should be formatted this way
```python3
"""
The Description
{space here}
Parameters
 ----------
entry_name: type   (no space between double dot and entry_name).
{indentation here}Description of the entry
entry_name2: type   (no space between double dot and entry_name2).
{indentation here}Description of the entry
{space here}
Returns
-------

"""
```

**Comment by Ipuch** [comment]
Please add a small unit test in tests folder after that and we are good.

**Comment by ANaaim** [comment]
Thanks for your comment !

**Comment by ANaaim** [comment]
Just to let you know : 
```python
# Just to let you know how Axis was imported
from bionc.bionc_numpy.natural_axis import Axis

vrshank = lambda m, bio: Axis(start=Marker(name='right_ankle',position=m["right_ankle"]), end=Marker(name='right_knee',position=m["right_knee"])).to_axis()
```
Give the following error : 
AttributeError: 'Axis' object has no attribute 'to_axis'


==> Now I remember that was the kind of error that make me do in the first time the function from_start_to_end.

Should we create the function to_axis in the NaturalAxis object ?

**Comment by ANaaim** [comment]
Erratum : it works but the line should have been : 

```python
vrshank = lambda m, bio: Axis(start=Marker(name='right_ankle',position=m["right_ankle"]), end=Marker(name='right_knee',position=m["right_knee"])).to_axis(
```

**Comment by ANaaim** [comment]
*[`bionc/model_creation/natural_axis_template.py` line 56 at r1](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfL_6tBASdqX2ciNl_C:-NfUgMF79keoEiQ1Pnu-:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/6224566e7e2a381c0dfba2856e8c5b1173ae62b9/bionc/model_creation/natural_axis_template.py#L56)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Please remove
</blockquote></details>

Done

**Comment by ANaaim** [comment]
*[`bionc/model_creation/natural_axis_template.py` line 51 at r2](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfRTUlUDfDHJMYzksrM:-NfV1eO80PBsvCbws7HS:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/ebdd5120ec7b3ca5a91eb855d4c2ca5978dc05ee/bionc/model_creation/natural_axis_template.py#L51)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

it should be formatted this way
```python3
"""
The Description
{space here}
Parameters
 ----------
entry_name: type   (no space between double dot and entry_name).
{indentation here}Description of the entry
entry_name2: type   (no space between double dot and entry_name2).
{indentation here}Description of the entry
{space here}
Returns
-------

"""
```
</blockquote></details>

Done

**Review by ANaaim — COMMENTED** [review]
Unit test have been added and blacked

> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/89#-:-NfV1hQO1eC2sJN98Hyi:b-vityke)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Ipuch)

**Review by Ipuch — CHANGES_REQUESTED** [review]
Last review but not least.


> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/89)* status: all files reviewed, 5 unresolved discussions (waiting on @ANaaim)

___
*[`bionc/model_creation/natural_axis_template.py` line 47 at r3](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfVwxRSAINvzvi8ep5I:-NfVwxRTBp0E_7BfWEYi:b-lr9jtp) ([raw file](https://github.com/Ipuch/bioNC/blob/48287bc778a4c9f2a83c02827bce13e1fde0754c/bionc/model_creation/natural_axis_template.py#L47)):*
> ```Python
> 
>     @staticmethod
>     def normalized_cross_product(m, bio, v1: np.ndarray, v2: np.ndarray) -> np.ndarray:
> ```

(m: dict[str, float], bio: "BiomechanicalModel", ...



_Code quote:_
```Python
m
```
___
*[`bionc/model_creation/natural_axis_template.py` line 53 at r3](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfVxWFQDKY-OfDuu7Qe:-NfVxWFQDKY-OfDuu7Qf:b-2927hp) ([raw file](https://github.com/Ipuch/bioNC/blob/48287bc778a4c9f2a83c02827bce13e1fde0754c/bionc/model_creation/natural_axis_template.py#L53)):*
> ```Python
>         Parameters
>         ----------
>         m: dict of markers
> ```

m: dict[str, float]
     Dictionnaries containing the location of markers in global frames
___
*[`bionc/model_creation/natural_axis_template.py` line 54 at r3](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfVxfpEAwI_4wS804px:-NfVxfpEAwI_4wS804py:b-j5f35r) ([raw file](https://github.com/Ipuch/bioNC/blob/48287bc778a4c9f2a83c02827bce13e1fde0754c/bionc/model_creation/natural_axis_template.py#L54)):*
> ```Python
>         ----------
>         m: dict of markers
>         bio: BiomechanicalModel
> ```

bio: BiomechanicalModel
     The model as it is constructed at that particular time. It is useful if some values must be obtained from previously computed values
___
*[`tests/test_natural_axis_template.py` line 7 at r3](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfVyYqT4yQkz9O2JllD:-NfVyYqT4yQkz9O2JllE:b-gfmc22) ([raw file](https://github.com/Ipuch/bioNC/blob/48287bc778a4c9f2a83c02827bce13e1fde0754c/tests/test_natural_axis_template.py#L7)):*
> ```Python
>     from bionc.model_creation.natural_axis_template import AxisTemplate
> 
>     vec1 = np.zeros((4, 2))
> ```

set more stupid values like np.array([[1, 2],[3, 4],[5, 6],[7, 8]]), because with  zeros you don't test enough the output.
___
*[`tests/test_natural_axis_template.py` line 15 at r3](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfVz-CmEgBhgHXYDUoE:-NfVz-CmEgBhgHXYDUoF:b-8u2njn) ([raw file](https://github.com/Ipuch/bioNC/blob/48287bc778a4c9f2a83c02827bce13e1fde0754c/tests/test_natural_axis_template.py#L15)):*
> ```Python
>     normalized_cross_product = AxisTemplate.normalized_cross_product(None, None, vec1, vec2)
> 
>     assert (normalized_cross_product == cross_vec).all()
> ```

Test actual values in output. with np.testing.assert_array_almost_equal(expected, output)

**Comment by ANaaim** [comment]
*[`bionc/model_creation/natural_axis_template.py` line 54 at r3](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfVxfpEAwI_4wS804px:-NfW2geQ2vscxHnPm1sf:b-x1rhgc) ([raw file](https://github.com/Ipuch/bioNC/blob/48287bc778a4c9f2a83c02827bce13e1fde0754c/bionc/model_creation/natural_axis_template.py#L54)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

bio: BiomechanicalModel
     The model as it is constructed at that particular time. It is useful if some values must be obtained from previously computed values
</blockquote></details>

Done 
==> All this former modification should be done on a lot of function as well I think.

**Comment by ANaaim** [comment]
*[`bionc/model_creation/natural_axis_template.py` line 47 at r3](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfVwxRSAINvzvi8ep5I:-NfW3-Ly14c8lqY_Mx11:bp0hcwk) ([raw file](https://github.com/Ipuch/bioNC/blob/48287bc778a4c9f2a83c02827bce13e1fde0754c/bionc/model_creation/natural_axis_template.py#L47)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

(m: dict[str, float], bio: "BiomechanicalModel", ...
</blockquote></details>

Done not sure if the BiomechanicalModel should have been or not inside parenthesis

**Comment by ANaaim** [comment]
*[`bionc/model_creation/natural_axis_template.py` line 53 at r3](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfVxWFQDKY-OfDuu7Qe:-NfW363m1q2IiviCmxNm:bb6un1j) ([raw file](https://github.com/Ipuch/bioNC/blob/48287bc778a4c9f2a83c02827bce13e1fde0754c/bionc/model_creation/natural_axis_template.py#L53)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

m: dict[str, float]
     Dictionnaries containing the location of markers in global frames
</blockquote></details>

Done

**Review by Ipuch — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/89)* status: all files reviewed, 3 unresolved discussions (waiting on @ANaaim)

___
*[`bionc/model_creation/natural_axis_template.py` line 47 at r3](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfVwxRSAINvzvi8ep5I:-NfW3maa-xzYJtn3j1j5:bjcrwsg) ([raw file](https://github.com/Ipuch/bioNC/blob/48287bc778a4c9f2a83c02827bce13e1fde0754c/bionc/model_creation/natural_axis_template.py#L47)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

Done not sure if the BiomechanicalModel should have been or not inside parenthesis
</blockquote></details>

" " are made to prevent circular import problem if works without that's better.
___
*[`bionc/model_creation/natural_axis_template.py` line 54 at r3](https://reviewable.io/reviews/Ipuch/bioNC/89#-NfVxfpEAwI_4wS804px:-NfW3vVW1wz8anoPKRM7:b-2dr0oy) ([raw file](https://github.com/Ipuch/bioNC/blob/48287bc778a4c9f2a83c02827bce13e1fde0754c/bionc/model_creation/natural_axis_template.py#L54)):*
<details><summary><i>Previously, ANaaim (Alexandre Naaim) wrote…</i></summary><blockquote>

Done 
==> All this former modification should be done on a lot of function as well I think.
</blockquote></details>

In another PR maybe, or depending on if you are willing to do it.

**Comment by Ipuch** [comment]
When test pass I accept.

**Review by Ipuch — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Ipuch/bioNC/89)* status: all files reviewed, 1 unresolved discussion (waiting on @ANaaim)

**Pull request merged**
