### PR TITLE
Creation of full coverage of natural_velocities

### PR DESCRIPTION
**Pull request by ANaaim**
This is my first test of developing a test + doing a pull request.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ipuch/bionc/12)

### CODE REVIEW

**Comment by Ipuch** [comment]
Why did you closed the issue ? 

To black you code run the command
´´´black . -l120

**Comment by ANaaim** [comment]
I reopend it and I saw that for the blacke to be correct it was necessary to add the option -l120

De : Pierre Puchaud ***@***.***>
Envoyé : vendredi 21 octobre 2022 13:58
À : Ipuch/bioNC ***@***.***>
Cc : NAAIM ALEXANDRE ***@***.***>; State change ***@***.***>
Objet : Re: [Ipuch/bioNC] Creation of full coverage of natural_velocities (PR #12)


Why did you closed the issue ?

To black you code run the command
´´´black . -l120

**Comment by Ipuch** [comment]
Also black needs to be run in the folder bioNC

**Comment by ANaaim** [comment]
Sorry for closing i thinked that a needed a new pull request to be able to add modification....

**Comment by Ipuch** [comment]
No trouble, it could have been anything, just asking. :)

**Pull request closed without merging**
